version: '3'

tasks:
  build:
    desc: Builds the executable application
    deps: [ pack ]
    cmds:
      - go build -v -i -o out/ cmd/update.go

  release:
    desc: Builds executables for Windows (amd64) and Linux (amd64, armhf)
    deps: [ pack ]
    cmds:
      - GOOS=windows GOARCH=amd64 go build -v -i -o out/update_windows_amd64.exe cmd/update.go
      - GOOS=linux GOARCH=amd64 go build -v -i -o out/update_linux_amd64 cmd/update.go
      - GOOS=linux GOARCH=arm go build -v -i -o out/update_linux_arm cmd/update.go

  pack:
    desc: Packs the assets into a .go file
    deps: [ assets ]
    dir: lib/html
    cmds:
      - go generate -v
    sources:
      - ../../resources/output.css
    generates:
      - style.go

  assets:
    desc: Creates the assets using yarn
    dir: resources
    cmds:
      - yarn
      - yarn run build
    sources:
      - styles.css
    generates:
      - output.css
    env:
      NODE_ENV:
        sh: echo {{if .DEV}} development {{else}} production {{end}}
