version: '3'

tasks:
  build:
    desc: Builds the executable application for the current platform
    deps: [ assets ]
    cmds:
      - go build -v -o out/ cmd/update.go

  assets:
    desc: Creates the assets using yarn
    dir: resources
    cmds:
      - yarn
      - yarn run build
