import { Link, Text } from '@geist-ui/core'

console.log(__COMMIT__HASH__)

const AppFooter = () => {
  const gitInfo = __COMMIT__HASH__
  const version = gitInfo.tag.length > 0 ? gitInfo.tag : gitInfo.commit
  const commitUrl = 'https://github.com/LukWebsForge/TldrProgress/commit/' + gitInfo.commit

  return (
    <Text p>
      Generated by{' '}
      <Link icon href="https://github.com/LukWebsForge/TldrProgress" target="_blank">
        tldr-translation-progress
      </Link>{' '}
      • Version{' '}
      <Link href={commitUrl} target="_blank">
        {version}
      </Link>{' '}
      • Thanks for using this site
    </Text>
  )
}

export { AppFooter }
