import {DataContext, OperatingSystem, TranslationStatus} from "./Data";
import * as React from "react";

const JumpList = () => {
    const data = React.useContext(DataContext);

    const listItems = Object.keys(data!.entries).map((value, index, array) =>
        <a href={'#' + value} className="hover:text-blue-500" key={value}>
            {value}{index < array.length - 1 ? ' - ' : ''}
        </a>
    );

    return <div className="my-10">
        <h3 className="text-2xl p-5">Quick Jump List</h3>
        {listItems}
    </div>
}

const DataTable = () =>
    <table className="text-center border-opacity-50 mx-auto">
        <DataTableHeader/>
        <DataTableBody/>
    </table>;

const DataTableHeader = () => {
    const data = React.useContext(DataContext);

    const languageRows = data!.languages
        .map((lang) => <th className="px-2 py-4 border border-gray-200" key={lang}>{lang}</th>);

    return <thead className="sticky top-0 bg-gradient-to-b from-white via-white">
    <tr>
        <th className="px-2 py-4 border border-gray-200">page</th>
        {languageRows}
    </tr>
    </thead>
}

const DataTableBody = () => {
    const data = React.useContext(DataContext);

    const osSections = Object.keys(data!.entries).map((os) =>
        <React.Fragment key={os}>
            <DataTableOSHeader os={os}/>
            <DataTableOSPages os={os}/>
        </React.Fragment>
    );

    return <tbody className="text-sm">{osSections}</tbody>
}

interface OsProps {
    os: OperatingSystem,
}

interface OsPageProps extends OsProps {
    pageName: string,
}

const DataTableOSHeader = ({os}: OsProps) => {
    const data = React.useContext(DataContext);
    const osProgress = data!.entries[os].progress;

    const percentages = data!.languages
        .map((lang) => <td className="px-1 py-2" key={lang}>{osProgress[lang]}%</td>);

    return <tr className="border border-gray-200 bg-indigo-300 p-4">
        <th className="text-base px-1 py-2" id={os}>{os}</th>
        {percentages}
    </tr>
}

const DataTableOSPages = ({os}: OsProps) => {
    const data = React.useContext(DataContext);
    const osPages = data!.entries[os].pages;

    const pages = Object.keys(osPages)
        .map((page) => <DataTableOSPageRow os={os} pageName={page} key={page}/>);

    return <>{pages}</>;
}

enum GitHubFileAction {
    view,
    create
}

const DataTableOSPageRow = ({os, pageName}: OsPageProps) => {
    const data = React.useContext(DataContext);
    const pageData = data!.entries[os].pages[pageName];

    function handleClick(action: GitHubFileAction, language: string) {
        const win = window.open(getGitHubPageUrl(action, os, pageName, language));
        if (win != null)
            win.focus();
    }

    const cells = data!.languages.map((lang) => {
        if (lang in pageData.status) {
            const status = pageData.status[lang];
            switch (status) {
                case TranslationStatus.Translated:
                    return <td className="bg-green-200 cursor-pointer" key={lang}
                               onClick={() => handleClick(GitHubFileAction.view, lang)}>✔</td>
                case TranslationStatus.Outdated:
                    return <td className="bg-yellow-200 cursor-pointer" key={lang}
                               onClick={() => handleClick(GitHubFileAction.view, lang)}>⚠</td>
                default:
                    return <td>?</td>
            }
        } else {
            return <td className="bg-red-200 cursor-pointer" key={lang}
                       onClick={() => handleClick(GitHubFileAction.create, lang)}>✖</td>
        }
    });

    return <tr className="border border-gray-200">
        <td className="text-left text-base p-1">{pageName}</td>
        {cells}
    </tr>
}

const getGitHubPageUrl = (action: GitHubFileAction, os: string, page: string, language: string) => {
    const languageSuffix = language === 'en' ? '' : '.' + language

    const baseUrl = "https://github.com/tldr-pages/tldr";
    const filePath = `/master/pages${languageSuffix}/${os}/${page}.md`

    if (action === GitHubFileAction.create) {
        return baseUrl + "/new" + filePath + `?filename=${page}.md`;
    } else if (action === GitHubFileAction.view) {
        return baseUrl + "/blob" + filePath;
    } else {
        throw new Error('Unknown GitHubFileAction: ' + action);
    }
}

const Footer = () => {
    const data = React.useContext(DataContext);

    return (
        <div className="my-6 text-center text-gray-700">
            Thanks for using this site •
            Generated by <a href="https://github.com/LukWebsForge/TldrProgress">tldr-translation-progress</a> •
            Last updated {data!.last_update}
        </div>
    )
}

export {JumpList, DataTable, Footer};
