name: Go (Release)

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build:
    name: Build (Release)
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Setup Task
      run: curl -sL https://taskfile.dev/install.sh | sh
    
    - name: Build using Taskfile.yml
      run: ./bin/task release
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled-application-amd64-ubuntu
        path: out/*

    - name: Publish
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          out/update_linux_amd64
          out/update_linux_arm
          out/update_windows_amd64
        draft: true
